### ISSUE TITLE
Convert Skeletor SWC format to archi tree skeleton

### ISSUE THREAD

**Issue by davodogster** [umr-amap/aRchi#12]
Hi @oliviermartin7 

I have a tree skeleton with edges and vertices like this in SWC Skeletor (github) format:
![image](https://user-images.githubusercontent.com/46079516/227090369-5724f581-d941-464e-932e-03118d973948.png)

Do you think it's easy to convert it to the aRchi skeleton format so we can derive tree params/architecture metrics from it?
Please let me know if you can assist or have suggestions.

Cheers, Sam

**Comment by oliviermartin7** [comment]
Hi Sam,

Yes could work !
I suggest you use _model= "simpletree"_ with _read_QSM_ function. Your input has to be like this :

 startX;  startY ; startZ ; endX ; endY ; radius ; axis_ID; branching_order 

Be consistent with the colum order. _axis_ID_ and _branching_order_ can be 0 and will be recalculated when using build_archi function.

Best

Olivier

**Comment by davodogster** [comment]
I notice no 'endZ' so is that not required? @oliviermartin7 
My second Q is we also have the skeleton in MTG format. https://mtg.readthedocs.io/en/latest/user/intro.html#mtg-file
Do you think it's possible to do the same with MTG to aRchi?

I will plan to try this.

Thank you!
Sam

**Comment by oliviermartin7** [comment]
@davodogster. oups !  You're right I forgot the z. So it is:

startX; startY ; startZ ; endX ; endY ; endZ; radius ; axis_ID; branching_order

For MTG, it is something we have to do for a while but we did not yet... If you are keen to code it would be awesome to add it to aRchi !!

Best,

Olivier

@VEZY

**Comment by VEZY** [comment]
Yes I didn't have time to get into this yet. @davodogster you can look into this repo for the MTG format: https://github.com/VEZY/XploRer/

You can read an MTG, and then extract its content as a data.frame with [data.tree::ToDataFrameTree](https://rdrr.io/pkg/data.tree/man/as.data.frame.Node.html). An example is [given here](https://vezy.github.io/XploRer/articles/XploRer.html#printextract-variables).

The full doc is here: https://vezy.github.io/XploRer/index.html

Keep in mind this package is currently in a stale state because R is too slow for heavy computations, so I rapidly switched to Julia and developed [this package](https://vezy.github.io/MultiScaleTreeGraph.jl/stable/) instead. So XploRer lacks a lot of features compared to MultiScaleTreeGraph.jl.

**Comment by oliviermartin7** [comment]
Thanks a lot Rémi for the information @VEZY !!
