### ISSUE TITLE
Create QSM in R

### ISSUE THREAD

**Issue by Saadi4469** [umr-amap/aRchi#8]
Hello, 

Thank you for the wonderful package, is there a way to create `QSM` in `R`? I don't have access to `MATLAB` to create QSMs nor am I familiar with it. 

Thank you

**Comment by oliviermartin7** [comment]
Hi,

Yes you can dot it. Please, check the readme:

Since the version 2.1.0 of the package, aRchi also provides the possibility to generate QSMs. To do so, three functions are provided :

    skeletonize_pc() allow to build a skeleton.
    smooth_skeleton().
    add_radius() computes the radius of each cylinder based on point distance to the skeleton.

The aRchi's QSM method was designed to build very detailed QSMs from high quality TLS scans. However, it also allow to quickly reconstruct the coarse architecture of large point clouds of lower quality. A basic explaination of QSMs building in aRchi is shown in the figure bellow. 

cheers,

Olivier
