### ISSUE TITLE
Improve cylinder radius for the stem

### ISSUE THREAD

**Issue by davodogster** [umr-amap/aRchi#9]
Hi this setting seems to give good radius for branches but too thin for them stem. Perhaps it is because I chopped the top off the point cloud?

Tree3_archi=add_radius(Tree_skel, sec_length = 0.02, by_axis = TRUE, method = "median")

![image](https://user-images.githubusercontent.com/46079516/196582827-3b0828cd-fb53-44ca-b2e2-f6e2c0b0c530.png)

Also, this small tree has 50K points. How many points do you think aRchi can handle for a dense point cloud, mature pine tree (300-800K points), for aRchi skeletonization, radius, and QSM computation?

Thanks!

**Comment by oliviermartin7** [comment]
Hi,

No it is not because you chopped the top, this should not have any effect. Did you try another set of parameters ? 
Hard to say for the number of points. The reconstruction uncertainties with TLS data come most of the time from occlusion or noise, but rarely from the density. The point cloud you show seem to be good enough. 

Best
